
SELECT CONVERT(DATETIME, '10-23-1990', 110) FROM Checkout


SELECT convert(VARCHAR(10),co.since,5) FROM Checkout co 

SELECT CONVERT(VARCHAR(10), GETDATE(), 105) AS [MM-DD-YYYY]

SELECT convert(DATETIME, until,110) FROM Checkout

ALTER TABLE Checkout
ALTER COLUMN until DATETIME

UPDATE Checkout SET since='9-27-1990'WHERE BID='3F00ED8804'

SET DATE